package swp.se1889.g1.rice_store.research;

import com.zaxxer.hikari.HikariDataSource;
import com.zaxxer.hikari.HikariPoolMXBean;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.sql.DataSource;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.lang.management.GarbageCollectorMXBean;
import java.lang.management.ManagementFactory;
import java.lang.management.MemoryMXBean;
import java.lang.management.ThreadMXBean;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;
import java.util.concurrent.locks.LockSupport;

/**
 * Arrival Sweep Benchmark (E0 + E2 of validation plan; Framework v3 Sections 3, 5, 7.3)
 * <p>
 * PURPOSE
 * Validate the M/M/c model in the region where its formulas are actually defined (ρ < 1),
 * by generating an OPEN-LOOP POISSON arrival process at controlled arrival rates λ,
 * instead of the closed burst submission used by PoolSweepValidationBenchmark.
 * <p>
 * WHY THIS EXISTS (root-cause fix)
 * The previous benchmark measured λ as REQUESTS / submission_window → burst rate (~10^5 rps),
 * which forced ρ → 0.9999 in every configuration and made the Erlang C denominator (1-ρ)
 * degenerate. This benchmark controls ρ directly:
 * λ_target = ρ_target · c · μ,   μ estimated at low load (ρ ≈ 0).
 * <p>
 * DESIGN
 * Assumption A1 (Poisson arrivals): inter-arrival gaps ~ Exponential(λ), generated by a
 * dedicated dispatcher thread with absolute-deadline scheduling. Achieved λ and the
 * coefficient of variation (CV) of realized gaps are recorded (CV ≈ 1 ⇒ Poisson-like).
 * Assumption A4 (pool is bottleneck): pool fixed at c = POOL_SIZE = 50.
 * E[N_q] is measured directly from HikariPoolMXBean.getThreadsAwaitingConnection(),
 * sampled every SAMPLE_MS during the measurement window — no model-estimated queue,
 * no circularity.
 * Predictions (P_wait, E[N_q], E[W]) are computed and WRITTEN TO FILE before any
 * measurement at the corresponding operating point (Framework §6: prediction before
 * measurement).
 * Both execution models run over the same service system:
 * VT = virtual thread per request; PT = platform thread per request.
 * Run order of (mode × ρ × repetition) cells is randomized (fixed seed) to decorrelate
 * environmental drift from operating point.
 * <p>
 * OPERATING POINTS
 * ρ ∈ {0.30, 0.50, 0.70, 0.85, 0.95, 1.05}
 * ρ < 1 points validate the model quantitatively.
 * ρ = 1.05 is intentionally unstable: it demonstrates Region IV behavior. No PASS/FAIL
 * verdict is assigned there (M/M/c steady state does not exist); it is reported as
 * boundary-crossing evidence only.
 * <p>
 * OUTPUTS (data/)
 * ARRIVAL_SWEEP_PREDICTIONS_<ts>.csv — frozen model predictions per ρ (written first)
 * ARRIVAL_SWEEP_BOUNDARIES_<ts>.csv  — predicted λ at region boundaries (§3.3 / §5)
 * ARRIVAL_SWEEP_RAW_<ts>.csv         — one row per repetition
 * ARRIVAL_SWEEP_SUMMARY_<ts>.csv     — per (mode, ρ): mean ± std ± CI95
 * ARRIVAL_SWEEP_VALIDATION_<ts>.csv  — prediction vs measurement, ρ < 1 only
 * <p>
 * RUNTIME
 * Default: 6 ρ × 2 modes × 5 reps × (10s warmup + 45s measure + drain) ≈ 1.5–2 h.
 * Override via -Darrival.reps, -Darrival.warmup, -Darrival.measure.
 */
@Component
@Profile("arrival-sweep")
public class ArrivalSweepBenchmark implements CommandLineRunner {

    @Autowired
    private DataSource dataSource;

    // ===== EXPERIMENT CONFIG =====

    private static final int POOL_SIZE = intProp("arrival.pool", 50);
    /**
     * Fine-grained ρ grid: {0.60, 0.65, 0.75, 0.80} added around the breakpoint ρ* ≈ 0.70
     * to tighten the bootstrap 95% CI on the piecewise regression breakpoint.
     * (Reviewer request: original CI [0.50, 0.70] too wide due to sparse grid.)
     */
    private static final double[] RHO_TARGETS = {
            0.30, 0.50, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.95, 1.05
    };

    private static final int REPS = intProp("arrival.reps", 20);
    private static final int WARMUP_SECONDS = intProp("arrival.warmup", 10);
    private static final int MEASURE_SECONDS = intProp("arrival.measure", 30);
    private static final int DRAIN_TIMEOUT_S = intProp("arrival.drain", 180);

    private static final int SAMPLE_MS = 200;    // Hikari pending sampling period
    private static final int SYS_SAMPLE_TICKS = 5;      // heap/threads every 5th sample (1 s)
    private static final int MAX_IN_FLIGHT = 20_000; // safety valve (PT overload / OOM)
    private static final long RANDOM_ORDER_SEED = 42L;
    private static final int SIMULATED_LATENCY_MS = 50;
    //    private static final String WAITFOR_SQL =
//            String.format("WAITFOR DELAY '00:00:00.%03d'", SIMULATED_LATENCY_MS);
// Thay thế dòng 105-106 thành:
    private static final String WAITFOR_SQL =
            String.format(Locale.US, "SELECT pg_sleep(%.3f)", SIMULATED_LATENCY_MS / 1000.0);
    private static final long TEST_STORE_ID = 1L;

    // μ-estimation baseline: pool >> concurrent → ρ ≈ 0 → E[W] ≈ E[S]
    private static final int BASELINE_POOL = 200;
    private static final int BASELINE_CONCURRENT = 10;
    private static final int BASELINE_SAMPLES = 200;

    // Engineering thresholds (same rationale as PoolSweepValidationBenchmark)
    private static final double LATENCY_ERROR_THRESHOLD_PCT = 30.0;
    private static final double NQ_ERROR_THRESHOLD_PCT = 30.0;

    private enum Mode {VT, PT}

    // ===== ESTIMATED PARAMETERS =====
    private long baselineHeapMb = -1;
    private double baselineMeanMs = -1;   // E[S] at ρ ≈ 0
    private double mu = -1;   // 1/E[S], req/s per connection

    // ===== OUTPUT FILES =====
    private final String ts = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
    private final String FILE_PRED = "data/ARRIVAL_SWEEP_PREDICTIONS_" + ts + ".csv";
    private final String FILE_BOUND = "data/ARRIVAL_SWEEP_BOUNDARIES_" + ts + ".csv";
    private final String FILE_RAW = "data/ARRIVAL_SWEEP_RAW_" + ts + ".csv";
    private final String FILE_SUMMARY = "data/ARRIVAL_SWEEP_SUMMARY_" + ts + ".csv";
    private final String FILE_VAL = "data/ARRIVAL_SWEEP_VALIDATION_" + ts + ".csv";

    // ===================================================================
    // MAIN
    // ===================================================================

    @Override
    public void run(String... args) throws Exception {
        System.out.println("============================================================");
        System.out.println("  ARRIVAL SWEEP BENCHMARK  (open-loop Poisson, rho-targeted)");
        System.out.printf("  pool=%d  reps=%d  warmup=%ds  measure=%ds%n",
                POOL_SIZE, REPS, WARMUP_SECONDS, MEASURE_SECONDS);
        System.out.println("============================================================");

        estimateMu();

        // --- PHASE 1: freeze predictions BEFORE any sweep measurement (Framework §6) ---
        Map<Double, Prediction> predictions = new LinkedHashMap<>();
        try (PrintWriter w = openCsv(FILE_PRED)) {
            w.println("Rho_Target,Lambda_Target_rps,Model_P_wait,Model_E_Nq," +
                    "Model_E_Wq_ms,Model_Mean_Latency_ms,Model_Region,Model_Valid");
            for (double rho : RHO_TARGETS) {
                Prediction p = predict(rho);
                predictions.put(rho, p);
                w.printf(Locale.US, "%.2f,%.2f,%.4f,%.2f,%.2f,%.2f,%s,%s%n",
                        rho, p.lambda, p.pWait, p.eNq, p.eWqMs, p.meanLatencyMs,
                        p.region, p.steadyStateValid ? "YES" : "NO_(rho>=1)");
                System.out.printf(
                        "  [PRED] rho=%.2f  lambda=%.1f rps  P(wait)=%.3f  E[Nq]=%.1f  E[W]=%.1f ms  %s%n",
                        rho, p.lambda, p.pWait, p.eNq, p.meanLatencyMs, p.region);
            }
        }
        writeBoundaryPredictions();

        // --- PHASE 2: randomized measurement cells ---
        List<Cell> cells = new ArrayList<>();
        for (Mode m : Mode.values())
            for (double rho : RHO_TARGETS)
                for (int rep = 1; rep <= REPS; rep++)
                    cells.add(new Cell(m, rho, rep));
        Collections.shuffle(cells, new Random(RANDOM_ORDER_SEED));

        Map<String, List<RunResult>> byCell = new LinkedHashMap<>();
        try (PrintWriter raw = openCsv(FILE_RAW)) {
            raw.println("Mode,Rho_Target,Rep,Lambda_Target_rps,Lambda_Achieved_rps," +
                    "InterArrival_CV,Dispatched,Completed,Rejected,Success_Pct," +
                    "Throughput_rps,Mean_Latency_ms,P99_ms," +
                    "Nq_Hikari_Mean,Nq_Hikari_Max,Little_Nq_Check," +
                    "Heap_Mean_MB,Heap_Max_MB,Threads_Mean,Threads_Max," +
                    // === JFR / GC evidence columns (Phase 1 addition) ===
                    "GC_Collections,GC_Pause_Total_ms,GC_Pause_Mean_ms," +
                    "Alloc_Rate_MB_s,Heap_Delta_MB");
            int i = 0;
            for (Cell cell : cells) {
                i++;
                System.out.printf("%n[%d/%d] mode=%s rho=%.2f rep=%d%n",
                        i, cells.size(), cell.mode, cell.rho, cell.rep);
                RunResult r = runCell(cell.mode, predictions.get(cell.rho).lambda);
                writeRawRow(raw, cell, r);
                byCell.computeIfAbsent(cell.mode + "|" + cell.rho, k -> new ArrayList<>()).add(r);
            }
        }

        // --- PHASE 3: aggregate + validate against frozen predictions ---
        writeSummaryAndValidation(byCell, predictions);

        System.out.println("\n============================================================");
        System.out.printf("  DONE. mu=%.4f req/s/conn (E[S]=%.1f ms)%n", mu, 1000.0 / mu);
        System.out.printf("  Files: %s%n         %s%n         %s%n         %s%n         %s%n",
                FILE_PRED, FILE_BOUND, FILE_RAW, FILE_SUMMARY, FILE_VAL);
        System.out.println("============================================================");
    }

    // ===================================================================
    // mu ESTIMATION (rho ~ 0)
    // ===================================================================

    private void estimateMu() throws Exception {
        System.out.println("\n--- Baseline: estimating mu at rho~0 ---");
        System.gc();
        Thread.sleep(2000);
        baselineHeapMb = captureSystem().heapMb;

        setPoolSize(BASELINE_POOL);

        // JIT + connection-establishment warmup, excluded from E[S] estimation.
        // Without this, baseline E[S] was inflated ~20% vs steady-state (75 vs 63 ms).
        ExecutorService warm = Executors.newVirtualThreadPerTaskExecutor();
        CountDownLatch warmLatch = new CountDownLatch(100);
        for (int i = 0; i < 100; i++) {
            warm.submit(() -> {
                try {
                    performIoTask();
                } catch (Exception ignored) {
                } finally {
                    warmLatch.countDown();
                }
            });
        }
        warmLatch.await(120, TimeUnit.SECONDS);
        warm.shutdownNow();

        ExecutorService ex = Executors.newVirtualThreadPerTaskExecutor();
        List<Long> lats = Collections.synchronizedList(new ArrayList<>());
        Semaphore gate = new Semaphore(BASELINE_CONCURRENT);
        CountDownLatch latch = new CountDownLatch(BASELINE_SAMPLES);
        for (int i = 0; i < BASELINE_SAMPLES; i++) {
            gate.acquire();
            ex.submit(() -> {
                long t = System.nanoTime();
                try {
                    performIoTask();
                } catch (Exception ignored) {
                } finally {
                    lats.add(System.nanoTime() - t);
                    gate.release();
                    latch.countDown();
                }
            });
        }
        latch.await(120, TimeUnit.SECONDS);
        ex.shutdownNow();

        baselineMeanMs = lats.stream().mapToLong(Long::longValue).average()
                .orElse(SIMULATED_LATENCY_MS * 1_000_000.0) / 1_000_000.0;
        mu = 1000.0 / baselineMeanMs;
        System.out.printf("  E[S]=%.1f ms  ->  mu=%.4f req/s/conn  (n=%d samples, idle heap=%d MB)%n",
                baselineMeanMs, mu, lats.size(), baselineHeapMb);
    }

    // ===================================================================
    // PREDICTIONS
    // ===================================================================

    private Prediction predict(double rhoTarget) {
        double lambda = rhoTarget * POOL_SIZE * mu;
        boolean valid = rhoTarget < 1.0;
        double pWait = valid ? erlangC(POOL_SIZE, rhoTarget) : 1.0;
        double eNq = valid ? pWait * rhoTarget / (1.0 - rhoTarget) : Double.NaN;
        double eWqMs = valid ? pWait / (POOL_SIZE * mu * (1.0 - rhoTarget)) * 1000.0 : Double.NaN;
        double eWMs = valid ? eWqMs + 1000.0 / mu : Double.NaN;
        String region = pWait < 0.05 ? "Queue-free"
                : pWait < 0.50 ? "Queueing"
                  : pWait < 0.90 ? "Saturated"
                    : "Resource-Exhaustion";
        if (!valid) region = "UNSTABLE (rho>=1, Region IV)";
        return new Prediction(lambda, pWait, eNq, eWqMs, eWMs, region, valid);
    }

    /**
     * Predicted region-boundary arrival rates (Framework Section 3.3 / 5):
     * lambda_0    : P(wait) = 0.05      (SAFE -> EFFICIENT)
     * lambda_warn : E[W_q]  = 1/mu      (latency ~2x baseline; EFFICIENT -> DEGRADED)
     * lambda_deg  : rho     = 0.90
     * Analysis compares these against λ at which measured transitions occur (±10% target).
     */
    private void writeBoundaryPredictions() throws Exception {
        double lam0 = bisectLambda(l -> erlangC(POOL_SIZE, l / (POOL_SIZE * mu)) - 0.05);
        double lamWarn = bisectLambda(l -> {
            double rho = l / (POOL_SIZE * mu);
            return erlangC(POOL_SIZE, rho) / (POOL_SIZE * mu * (1.0 - rho)) - 1.0 / mu;
        });
        double lamDeg = 0.90 * POOL_SIZE * mu;
        try (PrintWriter w = openCsv(FILE_BOUND)) {
            w.println("Boundary,Condition,Predicted_Lambda_rps,Predicted_Rho");
            w.printf(Locale.US, "n0,P(wait)=0.05,%.2f,%.4f%n", lam0, lam0 / (POOL_SIZE * mu));
            w.printf(Locale.US, "n_warn,E[Wq]=1/mu,%.2f,%.4f%n", lamWarn, lamWarn / (POOL_SIZE * mu));
            w.printf(Locale.US, "n_deg,rho=0.90,%.2f,%.4f%n", lamDeg, 0.90);
        }
        System.out.printf("  [BOUNDARIES] lambda_0=%.1f  lambda_warn=%.1f  lambda_deg=%.1f rps%n",
                lam0, lamWarn, lamDeg);
    }

    /**
     * Bisection on lambda in (0, c*mu) for f(lambda) = 0, f increasing.
     */
    private double bisectLambda(java.util.function.DoubleUnaryOperator f) {
        double lo = 1e-6, hi = POOL_SIZE * mu * 0.9999;
        for (int i = 0; i < 200; i++) {
            double mid = (lo + hi) / 2;
            if (f.applyAsDouble(mid) < 0) lo = mid;
            else hi = mid;
        }
        return (lo + hi) / 2;
    }

    // ===================================================================
    // ONE MEASUREMENT CELL  (open-loop Poisson at fixed lambda)
    // ===================================================================

    private RunResult runCell(Mode mode, double lambda) throws Exception {
        setPoolSize(POOL_SIZE);
        System.gc();
        Thread.sleep(800);

        ExecutorService executor = (mode == Mode.VT)
                ? Executors.newVirtualThreadPerTaskExecutor()
                : Executors.newThreadPerTaskExecutor(
                Thread.ofPlatform().name("pt-req-", 0).factory());

        final long warmupNanos = TimeUnit.SECONDS.toNanos(WARMUP_SECONDS);
        final long measureNanos = TimeUnit.SECONDS.toNanos(MEASURE_SECONDS);
        final long t0 = System.nanoTime();
        final long measureStart = t0 + warmupNanos;
        final long measureEnd = measureStart + measureNanos;

        final List<Long> latencies = Collections.synchronizedList(new ArrayList<>());
        final AtomicInteger inFlight = new AtomicInteger();
        final AtomicInteger dispatchedMeas = new AtomicInteger();
        final AtomicInteger completedMeas = new AtomicInteger();
        final AtomicInteger successMeas = new AtomicInteger();
        final AtomicInteger rejected = new AtomicInteger();
        final AtomicLong firstMeasDispatch = new AtomicLong(0);
        final AtomicLong lastMeasDispatch = new AtomicLong(0);

        // --- snapshot GC counters BEFORE measurement window ---
        GcSnapshot gcBefore = snapshotGc();
        long heapAtWindowStart = captureSystem().heapMb;

        // --- background sampler: Hikari pending (ground-truth N_q), heap, threads ---
        final List<Long> nqSamples = Collections.synchronizedList(new ArrayList<>());
        final List<Long> heapSamples = Collections.synchronizedList(new ArrayList<>());
        final List<Long> threadSamples = Collections.synchronizedList(new ArrayList<>());
        final Thread sampler = Thread.ofPlatform().daemon().name("sweep-sampler").start(() -> {
            int tick = 0;
            while (!Thread.currentThread().isInterrupted()) {
                long now = System.nanoTime();
                if (now >= measureStart && now < measureEnd) {
                    nqSamples.add(getHikariPending());
                    if (++tick % SYS_SAMPLE_TICKS == 0) {
                        SystemSnapshot s = captureSystem();
                        heapSamples.add(s.heapMb);
                        threadSamples.add((long) s.threadCount);
                    }
                }
                if (now >= measureEnd) break;
                try {
                    Thread.sleep(SAMPLE_MS);
                } catch (InterruptedException e) {
                    break;
                }
            }
        });

        // --- dispatcher: exponential inter-arrival gaps, absolute-deadline scheduling ---
        // If the dispatcher falls behind (park granularity ~1 ms on some OSes), it dispatches
        // immediately, preserving the mean rate; realized-gap CV is reported as the A1 check.
        final List<Long> realizedGaps = new ArrayList<>();
        long nextDeadline = t0;
        long prevDispatch = -1;
        ThreadLocalRandom rnd = ThreadLocalRandom.current();
        while (nextDeadline < measureEnd) {
            long now = System.nanoTime();
            while (now < nextDeadline) {
                long remaining = nextDeadline - now;
                // Coarse OS timers (~15 ms on Windows) clump arrivals (observed gap CV 1.5-3.0).
                // Park until 2 ms before the deadline, then busy-spin for sub-ms precision.
                if (remaining > 2_000_000L) LockSupport.parkNanos(remaining - 2_000_000L);
                else Thread.onSpinWait();
                now = System.nanoTime();
            }
            final long dispatchTime = now;
            final boolean inWindow = dispatchTime >= measureStart && dispatchTime < measureEnd;
            if (inWindow) {
                if (prevDispatch > 0) realizedGaps.add(dispatchTime - prevDispatch);
                prevDispatch = dispatchTime;
                firstMeasDispatch.compareAndSet(0, dispatchTime);
                lastMeasDispatch.set(dispatchTime);
            }
            if (inFlight.get() >= MAX_IN_FLIGHT) {
                if (inWindow) rejected.incrementAndGet();
            } else {
                inFlight.incrementAndGet();
                if (inWindow) dispatchedMeas.incrementAndGet();
                try {
                    executor.submit(() -> {
                        long s = System.nanoTime();
                        boolean ok = false;
                        try {
                            performIoTask();
                            ok = true;
                        } catch (Exception ignored) {
                        } finally {
                            long lat = System.nanoTime() - s;
                            if (inWindow) {
                                latencies.add(lat);
                                completedMeas.incrementAndGet();
                                if (ok) successMeas.incrementAndGet();
                            }
                            inFlight.decrementAndGet();
                        }
                    });
                } catch (Throwable t) {
                    // PT mode under deep overload: native thread creation can fail (T_max).
                    // Recorded as rejection — this IS the Region IV phenomenon, not a crash.
                    inFlight.decrementAndGet();
                    if (inWindow) {
                        dispatchedMeas.decrementAndGet();
                        rejected.incrementAndGet();
                    }
                }
            }
            // Exponential(lambda) gap; clamp at 10 s to avoid pathological stalls at tiny lambda
            double gapSec = Math.min(-Math.log(1.0 - rnd.nextDouble()) / lambda, 10.0);
            nextDeadline += (long) (gapSec * 1e9);
        }

        // --- drain in-flight requests (their latencies still count for the window) ---
        long drainDeadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(DRAIN_TIMEOUT_S);
        while (inFlight.get() > 0 && System.nanoTime() < drainDeadline) Thread.sleep(100);
        sampler.interrupt();
        executor.shutdownNow();

        // --- snapshot GC counters AFTER measurement window ---
        GcSnapshot gcAfter = snapshotGc();
        long heapAtWindowEnd = captureSystem().heapMb;

        // --- GC delta metrics for this replicate ---
        long gcCollections = gcAfter.totalCollections - gcBefore.totalCollections;
        long gcPauseTotalMs = gcAfter.totalPauseMs - gcBefore.totalPauseMs;
        double gcPauseMeanMs = gcCollections > 0 ? (double) gcPauseTotalMs / gcCollections : 0.0;
        double heapDeltaMb = heapAtWindowEnd - heapAtWindowStart;
        // Allocation rate: use heap max - heap at window start as proxy
        //   (true allocation rate requires GC allocation counters not available in standard MXBean;
        //    heapDeltaMb / windowSec gives net accumulation rate; see §4.3 note in paper).
        double allocRateMbS = heapSamples.isEmpty() ? 0
                : (heapSamples.stream().mapToLong(Long::longValue).max().orElse(0)
                   - heapAtWindowStart) / (double) MEASURE_SECONDS;

        // --- reduce ---
        double windowSec = MEASURE_SECONDS;
        double achievedLambda = dispatchedMeas.get() / windowSec;

        double gapMean = realizedGaps.stream().mapToLong(Long::longValue).average().orElse(0);
        double gapStd = stddevL(realizedGaps, gapMean);
        double gapCv = gapMean > 0 ? gapStd / gapMean : 0;

        List<Long> sorted = new ArrayList<>(latencies);
        sorted.sort(Long::compare);
        double meanMs = sorted.isEmpty() ? 0
                : sorted.stream().mapToLong(Long::longValue).average().orElse(0) / 1e6;
        double p99Ms = sorted.isEmpty() ? 0
                : sorted.get(Math.min(sorted.size() - 1, (int) (sorted.size() * 0.99))) / 1e6;

        double nqMean = nqSamples.stream().mapToLong(Long::longValue).average().orElse(0);
        long nqMax = nqSamples.stream().mapToLong(Long::longValue).max().orElse(0);
        double heapMean = heapSamples.stream().mapToLong(Long::longValue).average().orElse(0);
        long heapMax = heapSamples.stream().mapToLong(Long::longValue).max().orElse(0);
        double thrMean = threadSamples.stream().mapToLong(Long::longValue).average().orElse(0);
        long thrMax = threadSamples.stream().mapToLong(Long::longValue).max().orElse(0);

        // Little's Law internal consistency: N_q ?= lambda * W_q  (W_q = W - E[S])
        double wqMeasSec = Math.max(meanMs - baselineMeanMs, 0) / 1000.0;
        double littleNq = achievedLambda * wqMeasSec;

        double throughput = completedMeas.get() / windowSec;
        double successPct = dispatchedMeas.get() > 0
                ? successMeas.get() * 100.0 / dispatchedMeas.get() : 0;

        System.out.printf(
                "  lambda: target=%.1f achieved=%.1f (CV=%.2f) | tp=%.1f rps | mean=%.0f ms " +
                        "P99=%.0f ms | Nq=%.1f (max %d, Little=%.1f) | heap=%.0f MB | threads=%.0f (max %d)" +
                        " | GC: %d events %.0f ms | allocRate=%.1f MB/s%s%n",
                lambda, achievedLambda, gapCv, throughput, meanMs, p99Ms,
                nqMean, nqMax, littleNq, heapMean, thrMean, thrMax,
                gcCollections, (double) gcPauseTotalMs, allocRateMbS,
                rejected.get() > 0 ? " | REJECTED=" + rejected.get() : "");

        return new RunResult(lambda, achievedLambda, gapCv,
                dispatchedMeas.get(), completedMeas.get(), rejected.get(), successPct,
                throughput, meanMs, p99Ms, nqMean, nqMax, littleNq,
                heapMean, heapMax, thrMean, thrMax,
                gcCollections, gcPauseTotalMs, gcPauseMeanMs, allocRateMbS, heapDeltaMb);
    }

    /**
     * Service task. The simulated I/O delay runs INSIDE the database (WAITFOR DELAY),
     * so the HikariCP connection is genuinely OCCUPIED for the whole service time.
     * E[S] therefore equals connection hold time - the quantity M/M/c actually models.
     * <p>
     * Previous version slept AFTER the query returned the connection to the pool:
     * hold time was ~13 ms, true capacity ~3,800 rps, and the entire first sweep ran
     * at effective rho <= 0.18 - no queueing ever formed (run 20260708_201658).
     */
    private void performIoTask() throws Exception {
        try (Connection conn = dataSource.getConnection();
             Statement st = conn.createStatement()) {
            //            try (ResultSet rs = st.executeQuery(
//                    "SELECT TOP 20 * FROM invoices WHERE store_id = " + TEST_STORE_ID)) {
//                while (rs.next()) { /* drain */ }
//            }
            try {
                st.execute(WAITFOR_SQL);
                try (ResultSet rs = st.executeQuery(
                        "SELECT * FROM invoices WHERE store_id = " + TEST_STORE_ID + " LIMIT 20")) {
                    while (rs.next()) ;
                }
            } catch (Exception e) {
                System.err.println("performIoTask error: " + e.getMessage());
                e.printStackTrace();
                throw e;
            }
        }
    }

    // ===================================================================
    // AGGREGATION + VALIDATION
    // ===================================================================

    private void writeSummaryAndValidation(Map<String, List<RunResult>> byCell,
                                           Map<Double, Prediction> preds) throws Exception {
        try (PrintWriter sum = openCsv(FILE_SUMMARY);
             PrintWriter val = openCsv(FILE_VAL)) {

            sum.println("Mode,Rho_Target,Reps,Lambda_Achieved_Mean,InterArrival_CV_Mean," +
                    "Throughput_Mean,Mean_Latency_ms,Std_Latency_ms,CI95_Latency_ms," +
                    "P99_ms_Mean,Nq_Mean,Std_Nq,CI95_Nq,Little_Nq_Mean," +
                    "Heap_Mean_MB,Heap_Max_MB,Threads_Mean,Threads_Max,Rejected_Total," +
                    // JFR / GC columns
                    "GC_Collections_Mean,GC_Pause_Total_ms_Mean,GC_Pause_Mean_ms," +
                    "Alloc_Rate_MB_s_Mean,Heap_Delta_MB_Mean");

            val.println("Mode,Rho_Target,Lambda_Target_rps,Model_Region," +
                    "Model_Mean_Latency_ms,Measured_Mean_Latency_ms,CI95_Latency_ms,Latency_Error_Pct," +
                    "Model_E_Nq,Measured_Nq,CI95_Nq,Nq_Error_Pct," +
                    "Measured_P99_ms,GC_Collections_Mean,GC_Pause_Total_ms_Mean," +
                    "Alloc_Rate_MB_s_Mean,Validation_Pass");

            for (Mode mode : Mode.values()) {
                for (double rho : RHO_TARGETS) {
                    List<RunResult> rs = byCell.get(mode + "|" + rho);
                    if (rs == null || rs.isEmpty()) continue;
                    Prediction p = preds.get(rho);

                    List<Double> lat = rs.stream().map(r -> r.meanMs).toList();
                    List<Double> nq = rs.stream().map(r -> r.nqMean).toList();

                    double latMean = mean(lat), latStd = stddev(lat), latCi = ci95(lat);
                    double nqMean = mean(nq), nqStd = stddev(nq), nqCi = ci95(nq);

                    sum.printf(Locale.US,
                            "%s,%.2f,%d,%.2f,%.3f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f," +
                                    "%.1f,%d,%.1f,%d,%d," +
                                    "%.2f,%.2f,%.2f,%.2f,%.2f%n",
                            mode, rho, rs.size(),
                            rs.stream().mapToDouble(r -> r.achievedLambda).average().orElse(0),
                            rs.stream().mapToDouble(r -> r.gapCv).average().orElse(0),
                            rs.stream().mapToDouble(r -> r.throughput).average().orElse(0),
                            latMean, latStd, latCi,
                            rs.stream().mapToDouble(r -> r.p99Ms).average().orElse(0),
                            nqMean, nqStd, nqCi,
                            rs.stream().mapToDouble(r -> r.littleNq).average().orElse(0),
                            rs.stream().mapToDouble(r -> r.heapMean).average().orElse(0),
                            rs.stream().mapToLong(r -> r.heapMax).max().orElse(0),
                            rs.stream().mapToDouble(r -> r.thrMean).average().orElse(0),
                            rs.stream().mapToLong(r -> r.thrMax).max().orElse(0),
                            rs.stream().mapToInt(r -> r.rejected).sum(),
                            // JFR / GC columns
                            rs.stream().mapToDouble(r -> r.gcCollections).average().orElse(0),
                            rs.stream().mapToDouble(r -> r.gcPauseTotalMs).average().orElse(0),
                            rs.stream().mapToDouble(r -> r.gcPauseMeanMs).average().orElse(0),
                            rs.stream().mapToDouble(r -> r.allocRateMbS).average().orElse(0),
                            rs.stream().mapToDouble(r -> r.heapDeltaMb).average().orElse(0));

                    if (!p.steadyStateValid) {
                        val.printf(Locale.US,
                                "%s,%.2f,%.2f,%s,NA,%.2f,%.2f,NA,NA,%.2f,%.2f,NA,%.2f,UNSTABLE_NOT_SCORED%n",
                                mode, rho, p.lambda, p.region, latMean, latCi, nqMean, nqCi,
                                rs.stream().mapToDouble(r -> r.p99Ms).average().orElse(0));
                        continue;
                    }

                    double latErr = Math.abs(p.meanLatencyMs - latMean) / Math.max(latMean, 1.0) * 100;
                    double nqErr = Math.abs(p.eNq - nqMean) / Math.max(nqMean, 0.1) * 100;
                    boolean pass = latErr < LATENCY_ERROR_THRESHOLD_PCT
                            && nqErr < NQ_ERROR_THRESHOLD_PCT;

                    val.printf(Locale.US,
                            "%s,%.2f,%.2f,%s,%.2f,%.2f,%.2f,%.1f%%,%.2f,%.2f,%.2f,%.1f%%,%.2f,%.2f,%.2f,%.2f,%s%n",
                            mode, rho, p.lambda, p.region,
                            p.meanLatencyMs, latMean, latCi, latErr,
                            p.eNq, nqMean, nqCi, nqErr,
                            rs.stream().mapToDouble(r -> r.p99Ms).average().orElse(0),
                            rs.stream().mapToDouble(r -> r.gcCollections).average().orElse(0),
                            rs.stream().mapToDouble(r -> r.gcPauseTotalMs).average().orElse(0),
                            rs.stream().mapToDouble(r -> r.allocRateMbS).average().orElse(0),
                            pass ? "PASS" : "FAIL");

                    System.out.printf(
                            "  [VAL] %s rho=%.2f | W: pred=%.0f meas=%.0f ms (err %.1f%%) | " +
                                    "Nq: pred=%.1f meas=%.1f (err %.1f%%) | GC=%d ev, pauseTotal=%.0fms | %s%n",
                            mode, rho, p.meanLatencyMs, latMean, latErr,
                            p.eNq, nqMean, nqErr,
                            (long) rs.stream().mapToDouble(r -> r.gcCollections).average().orElse(0),
                            rs.stream().mapToDouble(r -> r.gcPauseTotalMs).average().orElse(0),
                            pass ? "PASS" : "FAIL");
                }
            }
        }
    }

    // ===================================================================
    // ERLANG C (log-space; same method as PoolSweepValidationBenchmark)
    // ===================================================================

    private double erlangC(int c, double rho) {
        if (rho >= 1.0) return 1.0;
        if (c <= 0) return 0.0;
        double a = c * rho;
        double logA = a > 0 ? Math.log(a) : Double.NEGATIVE_INFINITY;
        double logNum = c * logA - logGamma(c + 1) - Math.log(1.0 - rho);
        double logSum = Double.NEGATIVE_INFINITY;
        for (int k = 0; k < c; k++) {
            double logTerm = (k == 0) ? 0.0 : k * logA - logGamma(k + 1);
            logSum = logSumExp(logSum, logTerm);
        }
        double r = Math.exp(logNum - logSumExp(logSum, logNum));
        return (Double.isNaN(r) || r < 0) ? 0.0 : Math.min(r, 1.0);
    }

    private double logSumExp(double a, double b) {
        if (a == Double.NEGATIVE_INFINITY) return b;
        if (b == Double.NEGATIVE_INFINITY) return a;
        double max = Math.max(a, b);
        return max + Math.log(Math.exp(a - max) + Math.exp(b - max));
    }

    private double logGamma(int n) {
        if (n <= 1) return 0.0;
        double r = 0.0;
        for (int i = 2; i < n; i++) r += Math.log(i);
        return r;
    }

    // ===================================================================
    // INFRASTRUCTURE
    // ===================================================================

    private long getHikariPending() {
        try {
            if (dataSource instanceof HikariDataSource h) {
                HikariPoolMXBean b = h.getHikariPoolMXBean();
                if (b != null) return b.getThreadsAwaitingConnection();
            }
        } catch (Exception ignored) {
        }
        return 0;
    }

    private void setPoolSize(int size) throws Exception {
        if (dataSource instanceof HikariDataSource h) {
            h.setMaximumPoolSize(size);
            h.setMinimumIdle(Math.min(size / 4 + 1, size));
            Thread.sleep(500);
        } else throw new IllegalStateException("DataSource is not HikariDataSource");
    }

    private SystemSnapshot captureSystem() {
        MemoryMXBean mem = ManagementFactory.getMemoryMXBean();
        ThreadMXBean thr = ManagementFactory.getThreadMXBean();
        return new SystemSnapshot(mem.getHeapMemoryUsage().getUsed() / (1024 * 1024),
                thr.getThreadCount());
    }

    private PrintWriter openCsv(String filename) throws Exception {
        java.io.File dir = new java.io.File("data");
        if (!dir.exists()) dir.mkdirs();
        return new PrintWriter(new FileWriter(filename, false));
    }

    private void writeRawRow(PrintWriter raw, Cell c, RunResult r) {
        raw.printf(Locale.US,
                "%s,%.2f,%d,%.2f,%.2f,%.3f,%d,%d,%d,%.1f,%.2f,%.2f,%.2f," +
                        "%.2f,%d,%.2f,%.1f,%d,%.1f,%d," +
                        "%d,%.2f,%.2f,%.2f,%.2f%n",
                c.mode, c.rho, c.rep, r.targetLambda, r.achievedLambda, r.gapCv,
                r.dispatched, r.completed, r.rejected, r.successPct,
                r.throughput, r.meanMs, r.p99Ms,
                r.nqMean, r.nqMax, r.littleNq,
                r.heapMean, r.heapMax, r.thrMean, r.thrMax,
                r.gcCollections, r.gcPauseTotalMs, r.gcPauseMeanMs,
                r.allocRateMbS, r.heapDeltaMb);
        raw.flush();
    }

    private double mean(List<Double> v) {
        return v.stream().mapToDouble(Double::doubleValue).average().orElse(0);
    }

    private double stddev(List<Double> v) {
        double m = mean(v);
        return Math.sqrt(v.stream().mapToDouble(x -> (x - m) * (x - m)).average().orElse(0));
    }

    private double stddevL(List<Long> v, double m) {
        return Math.sqrt(v.stream().mapToDouble(x -> (x - m) * (x - m)).average().orElse(0));
    }

    private double ci95(List<Double> v) {
        int n = v.size();
        return (n < 2) ? 0.0 : 1.96 * stddev(v) / Math.sqrt(n);
    }

    private static int intProp(String key, int def) {
        try {
            return Integer.parseInt(System.getProperty(key, String.valueOf(def)));
        } catch (NumberFormatException e) {
            return def;
        }
    }

    // ===================================================================
    // GC MEASUREMENT HELPERS
    // ===================================================================

    /**
     * Snapshot of all GarbageCollectorMXBean counters at a point in time.
     * Delta between two snapshots gives GC events and pause time during a window.
     * This uses the standard java.lang.management API (no JFR agent required).
     */
    private GcSnapshot snapshotGc() {
        long totalCollections = 0;
        long totalPauseMs = 0;
        for (GarbageCollectorMXBean gc : ManagementFactory.getGarbageCollectorMXBeans()) {
            long count = gc.getCollectionCount();
            long time = gc.getCollectionTime();
            if (count > 0) totalCollections += count;
            if (time > 0) totalPauseMs += time;
        }
        return new GcSnapshot(totalCollections, totalPauseMs);
    }

    // ===================================================================
    // RECORDS
    // ===================================================================

    private record Cell(Mode mode, double rho, int rep) {
    }

    private record SystemSnapshot(long heapMb, int threadCount) {
    }

    private record GcSnapshot(long totalCollections, long totalPauseMs) {
    }

    private record Prediction(
            double lambda, double pWait, double eNq, double eWqMs,
            double meanLatencyMs, String region, boolean steadyStateValid) {
    }

    private record RunResult(
            double targetLambda, double achievedLambda, double gapCv,
            int dispatched, int completed, int rejected, double successPct,
            double throughput, double meanMs, double p99Ms,
            double nqMean, long nqMax, double littleNq,
            double heapMean, long heapMax, double thrMean, long thrMax,
            // JFR / GC evidence fields
            long gcCollections, double gcPauseTotalMs, double gcPauseMeanMs,
            double allocRateMbS, double heapDeltaMb) {
    }
}
