spring.application.name=rice_store
server.port=9090
# === DATABASE CONNECTION ===
# Dam bao Port 1433 la dung voi Docker
#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=rice_store;encrypt=true;trustServerCertificate=true;packetSize=32767
#spring.datasource.username=sa
spring.datasource.url=jdbc:postgresql://localhost:5432/rice_store
spring.datasource.username=postgres
spring.datasource.password=StrongPassword!123
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# === HIKARI CP TUNING ===
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=20
# Tang Timeout len 120s (2 phut)
spring.datasource.hikari.connection-timeout=120000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
# === TOMCAT TUNING ===
# Mo max thread len 10000
server.tomcat.threads.max=10000
server.tomcat.threads.min-spare=100
server.tomcat.accept-count=5000
server.tomcat.max-connections=20000
# === JPA / HIBERNATE ===
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.format_sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
# === LOGGING ===
logging.level.root=INFO
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF
logging.level.com.zaxxer.hikari=ERROR
# === MISC ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=huybqhe180599@fpt.edu.vn
spring.mail.password=zdms kcvd tett uvpq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
